Repository wecode-bootcamp-korea/37-2nd-Cosegu-frontend, pull requests merged in 2022-10, with the labels that each got.

#2 [3기 강루비] global, theme 수정
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: 완료

#4 [37기 라용] 푸터 레이아웃 디자인 완료
  src/components/Footer/Footer.js
  src/components/Footer/FooterLeft/FooterLeft.js
  src/components/Footer/FooterLeft/LeftMenu.js
  src/components/FooterRight/FooterRight.js
  src/components/FooterRight/LinkSite.js
Labels: 완료

#1 [37기 라용] 헤더 레이아웃 디자인 완료
  .gitignore
  package-lock.json
  package.json
  src/components/Header/Header.js
  src/components/Header/HeaderIcon/HeaderIcon.js
  src/components/Header/HeaderIcon/LikeIcon.js
  src/components/Header/HeaderIcon/LoginIcon.js
  src/components/Header/HeaderIcon/LogoutIcon.js
  src/components/Header/HeaderMenu.js
  src/pages/Login/Login.js
  src/styles/GlobalStyle.js
Labels: 완료

#5 [37기 신주안] Add : 크루지원 레이아웃
  public/data/recruit.json
  src/index.js
  src/pages/CrewRecruit/CrewRecruit.js
  src/pages/CrewRecruit/components/Banner.js
  src/pages/CrewRecruit/components/HowToCrew.js
  src/pages/CrewRecruit/components/Interview.js
  src/pages/CrewRecruit/components/Intro.js
  src/pages/CrewRecruit/components/Recruit/CrewRecruits.js
  src/pages/CrewRecruit/components/Recruit/Recruit.js
  src/pages/CrewRecruit/components/Tab.js
  src/pages/CrewRecruit/components/Work.js
  src/styles/variables.js
Labels: 완료

#12 [37기 강루비] 찜한공고 레이아웃 완료, 하트 기능 완료
  public/data/data.json
  public/data/detail.json
  public/images/Detail/back_arrow.png
  public/images/Detail/heart_off.png
  public/images/Detail/heart_on.png
  public/images/test.png
  src/asset/images/back_arrow.png
  src/pages/WishList/DetailRightItem.js
  src/pages/WishList/WishList.js
  src/pages/WishList/components/DetailLeftItem.js
  src/pages/WishList/components/Popup.js
  src/styles/variables.js
Labels: 완료

#3 [37기 라용] 로그인 디자인 완료 / 소셜로그인 완료
  src/Router.js
  src/pages/Login/Login.js
  src/pages/Login/LoginBtn.js
  src/pages/Login/LoginInput.js
  src/pages/Login/SocialLogin/OAuth.js
  src/pages/Login/SocialLogin/SocialLogin.js
  src/pages/SignUp/SignUp.js
Labels: 멘토 리뷰 요청

#8 [37기 라용] 메인 페이지 디자인 완료 / 1차 기능 구현 완료
  package-lock.json
  package.json
  public/data/cardslide.json
  public/data/mainslide.json
  public/images/search_ico.png
  src/components/Search/Search.js
  src/components/Search/SearchField.js
  src/pages/Main/Main.js
  src/pages/Main/MainApplyFloat.js
  src/pages/Main/MainCardSlide.js
  src/pages/Main/MainCate/CategoryTab.js
  src/pages/Main/MainCate/MainCate.js
  src/pages/Main/MainPhotoGrid.js
  src/pages/Main/MainProcess.js
  src/pages/Main/MainSearch.js
  src/pages/Main/MainSlide.js
Labels: 완료

#13 [37기 라용] Add : 푸터 링크 연결 및 외부사이트 미니 팝업 추가 완료
  src/components/FooterRight/FooterRight.js
  src/components/FooterRight/LinkSite.js
Labels: 완료

#15 [37기 신주안] Add : config 파일 추가
  src/config.js
Labels: 멘토 리뷰 요청

#6 [37기 라용] Add : 마이페이지 정적 레이아웃 완료
  src/hooks/useLockBodyScroll.js
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/PageBody/PageBody.js
  src/pages/Mypage/PageBody/PageBodyApply/ModalApply/ModalApply.js
  src/pages/Mypage/PageBody/PageBodyApply/ModalApply/ModalApplyContents/ModalApplyContents.js
  src/pages/Mypage/PageBody/PageBodyApply/ModalApply/ModalApplyContents/UserApply.js
  src/pages/Mypage/PageBody/PageBodyApply/ModalApply/ModalApplyContents/UserAttatch.js
  src/pages/Mypage/PageBody/PageBodyApply/ModalApply/ModalApplyContents/UserCareer.js
  src/pages/Mypage/PageBody/PageBodyApply/ModalApply/ModalApplyContents/UserInfo.js
  src/pages/Mypage/PageBody/PageBodyApply/ModalApply/ModalApplyContents/UserLicense.js
  src/pages/Mypage/PageBody/PageBodyApply/ModalApply/ModalApplyContents/UserText.js
  src/pages/Mypage/PageBody/PageBodyApply/PageBodyApply.js
  src/pages/Mypage/PageBody/PageBodyQna.js
  src/pages/Mypage/PageBody/PageBodyTitle.js
  src/pages/Mypage/PageHeader/HeaderInfo.js
  src/pages/Mypage/PageHeader/PageHeader.js
Labels: 완료

#16 [37기 라용] Add : 헤더, 찜한 공고 숫자 표시, 목데이터로 기능 구현 완료
  public/data/likelist.json
  src/components/Header/HeaderIcon/LikeIcon.js
  src/pages/Login/Login.js
Labels: 멘토 리뷰 요청

#9 [37기 신주안] [Faq] 토큰 설정 완료
  public/data/faq.json
  src/asset/images/talk-ballon.png
  src/components/Search/Search.js
  src/config.js
  src/pages/CrewRecruit/components/Banner.js
  src/pages/CrewRecruit/components/Interview.js
  src/pages/CrewRecruit/components/Recruit/CrewRecruits.js
  src/pages/CrewRecruit/components/Work.js
  src/pages/Faq/Faq.js
  src/pages/Faq/FaqModal.js
  src/pages/Login/SocialLogin/OAuth.js
  src/pages/Login/SocialLogin/SocialLogin.js
  src/styles/variables.js
Labels: 완료

#18 [37기 라용] Add : 소셜 로그인 통신 테스트 완료 (머지 요청)
  src/Router.js
  src/config.js
  src/pages/Login/SocialLogin/OAuth.js
Labels: 완료

#11 [37기 신주안] [CrewRecruit-Function] Add : Scroll 탭 기능& 인터뷰 탭& 지원하기 기능 구현
  package-lock.json
  package.json
  public/data/recruit.json
  public/index.html
  src/config.js
  src/pages/CrewRecruit/CrewRecruit.js
  src/pages/CrewRecruit/components/HowToCrew.js
  src/pages/CrewRecruit/components/Interview.js
  src/pages/CrewRecruit/components/InterviewData.js
  src/pages/CrewRecruit/components/Intro.js
  src/pages/CrewRecruit/components/Recruit/JobOpening.js
  src/pages/CrewRecruit/components/Recruit/Recruit.js
  src/pages/CrewRecruit/components/Tab.js
  src/pages/CrewRecruit/components/Work.js
Labels: 멘토 리뷰 요청

#7 [37기 강루비] 지원하기 레이아웃 완료, 리스트 정렬 구현 완료, 상세페이지 레이아웃 완료, 기능 구현 중
  public/data/rec/recruit.json
  public/data/rec/skill.json
  public/images/rec/heart_off.png
  public/images/rec/heart_on.png
  public/images/rec/listType_ico_off.png
  public/images/rec/listType_ico_on.png
  public/images/rec/tileType_ico_off.png
  public/images/rec/tileType_ico_on.png
  src/Router.js
  src/asset/images/test.png
  src/components/Search/Search.js
  src/components/Search/SearchField.js
  src/pages/Recruitment/CategoryTab.js
  src/pages/Recruitment/LeftFilter.js
  src/pages/Recruitment/Recruit.js
  src/pages/Recruitment/Recruitment.js
  src/pages/Recruitment/RecruitmentDetail.js
  src/pages/Recruitment/Skill.js
  src/pages/Recruitment/components/DetailLeftItem.js
  src/pages/Recruitment/components/DetailRightItem.js
  src/pages/Recruitment/components/RecItem.js
Labels: 멘토 리뷰 요청

#17 [37기 라용] Add : 마이페이지 1차 데이터 전송 완료
  public/data/mypageinfo.json
  src/config.js
  src/pages/Faq/FaqModal.js
  src/pages/Login/Login.js
  src/pages/Login/SocialLogin/OAuth.js
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/PageBody/PageBody.js
  src/pages/Mypage/PageBody/PageBodyApply/PageBodyApply.js
  src/pages/Mypage/PageBody/PageBodyQna.js
  src/pages/Mypage/PageHeader/HeaderInfo.js
  src/pages/Mypage/PageHeader/PageHeader.js
Labels: 추가 기능 구현 중
